version: '3.9'

services:
  web:
    build: .
    container_name: quiz_web
    command: daphne -b 0.0.0.0 -p 8000 quizAiChallenge.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=quizAiChallenge.settings
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: quiz_redis
    ports:
      - "6379:6379"   # chỉ cần khi debug
    restart: unless-stopped
